apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: linkerd-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            linkerd: "enabled"
  template:
    metadata:
      name: 'linkerd-crds-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/linkerd/linkerd2.git
        targetRevision: edge-26.9.1
        path: charts/linkerd-crds
      destination:
        server: '{{server}}'
        namespace: linkerd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            trust-target: "linkerd"
        syncOptions:
          - ServerSideApply=true
