apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api-crds
  namespace: argocd
  annotations:
        argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            linkerd: "enabled"
  template:
    metadata:
      name: 'gateway-api-crds-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/kubernetes-sigs/gateway-api
        targetRevision: v1.6.2
        path: config/crd/standard
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
