apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            linkerd: "enabled"
  template:
    metadata:
      name: 'trust-manager-{{name}}'
    spec:
      project: default
      source:
        repoURL: oci://quay.io/jetstack/charts/trust-manager
        targetRevision: "0.24.0"
        chart: trust-manager
        helm:
          releaseName: trust-manager
          values: |
            app:
              trust:
                namespace: cert-manager
      destination:
        server: '{{server}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
